---
title: Guide to my country 2.0
hero_image: images/banner.png
description: Take your website design skills further!
theme: 红色
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: html/css
site_areas: coderdojo, projects
hardware: ''
software: html/css
version: 1
last_tested: 2017年1月1日
steps:
  - 
    title: 介绍
  - 
    title: Getting set up
  - 
    title: All the colours!
  - 
    title: Organising your page
  - 
    title: Design some themes
  - 
    title: Individual style
  - 
    title: See the code on other websites!
  - 
    title: Automatically adjust the size
  - 
    title: Animation
  - 
    title: Teach Tito to roll over!
