---
title: Guía de mi país 2.0
hero_image: images/banner.png
description: '¡Lleva las habilidades de diseño de tu sitio web aún más lejos!'
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: html-css-javascript
site_areas: coderdojo, projects
hardware: ''
software: html-css-javascript
version: 1
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: Preparación
  - 
    title: '¡Todos los colores!'
  - 
    title: Organizando tu página
  - 
    title: Diseña algunos temas
  - 
    title: Estilo individual
  - 
    title: '¡Mira el código en otros sitios web!'
  - 
    title: Ajustar automáticamente el tamaño
  - 
    title: Animación
  - 
    title: '¡Enséñale a Tito a darse la vuelta!'
