---
title: Guide to my country 2.0
hero_image: images/banner.png
description: Luați-vă abilitățile de design de site web în continuare!
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: html-css-JavaScript
site_areas: coderdojo, proiecte
hardware: ''
software: html-css-JavaScript
version: 1
last_tested: 01-01-2017
steps:
  - 
    title: Introducere
  - 
    title: Getting set up
  - 
    title: All the colours!
  - 
    title: Organising your page
  - 
    title: Design some themes
  - 
    title: Individual style
  - 
    title: See the code on other websites!
  - 
    title: Automatically adjust the size
  - 
    title: Animation
  - 
    title: Teach Tito to roll over!
