---
title: Sushi carte HTML / CSS intermedie
hero_image: images / banner.png
description: Migliora ulteriormente le tue capacità di progettazione del sito web!
theme: rosso
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: html-css-javascript
site_areas: coderdojo, progetti
hardware: ''
software: html-css-javascript
version: 1
last_tested: 2017/01/01
steps:
  - 
    title: introduzione
  - 
    title: Di cosa avrai bisogno
  - 
    title: Prepararsi
  - 
    title: Tutti i colori!
  - 
    title: Organizzazione della tua pagina
  - 
    title: Disegna alcuni temi
  - 
    title: Stile individuale
  - 
    title: Guarda il codice su altri siti web!
  - 
    title: Regola automaticamente le dimensioni
  - 
    title: Animazione
  - 
    title: Insegna a Tito di girarsi!
